server:
  port: 9081

spring:
  application:
    name: cloud-manager-auth-server
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.240.57:3306/cloud_manager?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: zplus
    password: nopassword
  cloud:
    nacos:
      discovery:
        server-addr: 47.106.240.57:8848
  #redis 配置
  redis:
    database: 0
    host: 47.106.240.57
    password: Zfakepw&3090
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    port: 6379

dubbo:
  scan:
    base-packages: com.zplus.cloud.alibabadubboserver.service
  protocol:
    name: dubbo
    port: -1
  #    serialization: kryo
  registry:
    address: spring-cloud://localhost
  provider:
    loadbalance: roundrobin
  cloud:
    subscribed-services: "dubbo-provider-service"

#消费者配置
#spring:
#  application:
#    name: alibaba-dubbo-consumer
#  main:
#    allow-bean-definition-overriding: true
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 47.106.240.57:8848
#dubbo:
#  application:
#    qos-enable: false
#  protocol:
#    name: dubbo
#    port: -1
#  registry:
#    address: spring-cloud://localhost
#  cloud:
#    subscribed-services: "dubbo-provider-service"

management:
  endpoints:
    web:
      exposure:
        include: "*"

